#!/usr/bin/env julia
"""
Convert a terrain geometry HDF5 file (produced by create_terrain_geometry.jl)
to a CORSIKA-compatible binary PLY mesh file.

The HDF5 group must contain:
  vertices : (3, N) Float64  -- ECEF coordinates in metres (x, y, z)
  faces    : (3, M) Int64    -- triangle vertex indices, 0-based

Vertices are written as double-precision (Float64) values to preserve the
full ECEF coordinate range (~6.37 × 10^6 m).  CORSIKA's MeshLoader handles
both float32 and float64 PLY vertex properties.

Usage
-----
  julia --project=<project_dir> terrain_h5_to_ply.jl INPUT.h5 [options]

  Options:
    --group NAME    HDF5 group name  [default: first group with vertices/faces]
    --output PATH   Output PLY file  [default: terrain.ply]
"""

using ArgParse
using HDF5

const EARTH_RADIUS_M = 6.371e6

# ---------------------------------------------------------------------------
# PLY writer
# ---------------------------------------------------------------------------

"""
Write a binary_little_endian PLY with Float64 x,y,z vertices and
UInt8 count + UInt32 indices per face.  This is the format expected by
CORSIKA's MeshLoader::loadPLY.
"""
function write_ply_binary(filepath::AbstractString,
                          vertices::AbstractMatrix,
                          faces::AbstractMatrix)
    n_verts = size(vertices, 1)   # vertices is (N, 3)
    n_faces = size(faces, 1)      # faces    is (M, 3)

    header = "ply\n" *
             "format binary_little_endian 1.0\n" *
             "comment generated by terrain_h5_to_ply.jl\n" *
             "element vertex $(n_verts)\n" *
             "property double x\n" *
             "property double y\n" *
             "property double z\n" *
             "element face $(n_faces)\n" *
             "property list uchar uint vertex_indices\n" *
             "end_header\n"

    open(filepath, "w") do io
        write(io, header)
        for i in 1:n_verts
            write(io, htol(Float64(vertices[i, 1])))
            write(io, htol(Float64(vertices[i, 2])))
            write(io, htol(Float64(vertices[i, 3])))
        end
        for j in 1:n_faces
            write(io, UInt8(3))
            write(io, htol(UInt32(faces[j, 1])))
            write(io, htol(UInt32(faces[j, 2])))
            write(io, htol(UInt32(faces[j, 3])))
        end
    end

    size_mb = filesize(filepath) / 1e6
    println("  Wrote $(n_verts) vertices, $(n_faces) faces -> $(round(size_mb, digits=1)) MB")
end

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function find_default_group(fid::HDF5.File)::String
    for name in keys(fid)
        grp = fid[name]
        if isa(grp, HDF5.Group) && haskey(grp, "vertices") && haskey(grp, "faces")
            return name
        end
    end
    error("No group with 'vertices' and 'faces' found in HDF5 file.")
end

function report_altitude_stats(label::String, vertices::AbstractMatrix)
    # vertices is (N, 3)
    norms = [sqrt(vertices[i,1]^2 + vertices[i,2]^2 + vertices[i,3]^2)
             for i in 1:size(vertices, 1)]
    alts = norms .- EARTH_RADIUS_M
    println("  $(label) altitude: $(round(Int, minimum(alts))) .. " *
            "$(round(Int, maximum(alts))) m  " *
            "(mean $(round(Int, sum(alts)/length(alts))) m)")
end

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

function parse_args_main()
    s = ArgParseSettings(
        description = "Convert terrain geometry HDF5 to a CORSIKA-compatible PLY mesh.",
        add_help    = true,
    )
    @add_arg_table! s begin
        "input_h5"
            help     = "Input HDF5 terrain geometry file"
            arg_type = String
            required = true
        "--group"
            help     = "HDF5 group name (default: first group with vertices/faces)"
            arg_type = String
            default  = ""
        "--output"
            help     = "Output PLY file path"
            arg_type = String
            default  = "terrain.ply"
    end
    return ArgParse.parse_args(s)
end

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

function main()
    args = parse_args_main()

    println("Reading $(args["input_h5"]) ...")
    vertices, faces = h5open(args["input_h5"], "r") do f
        group_name = isempty(args["group"]) ? find_default_group(f) : args["group"]
        println("  Using group: $(group_name)")
        g = f[group_name]
        Float64.(read(g["vertices"])), Int64.(read(g["faces"]))
    end
    # vertices: (N, 3), faces: (M, 3) 0-based  [HDF5.jl reverses dims vs h5py]

    n_verts = size(vertices, 1)
    n_faces = size(faces, 1)
    println("  Vertices: $(n_verts)   Faces: $(n_faces)")
    report_altitude_stats("Terrain", vertices)

    out_dir = dirname(abspath(args["output"]))
    isempty(out_dir) || mkpath(out_dir)

    println("\nWriting PLY: $(args["output"]) ...")
    write_ply_binary(args["output"], vertices, faces)
    println("Done.")
end

main()
